### ISSUE TITLE
Past sessions for anonymous accounts

### ISSUE THREAD

**Issue by cindyccook** [antoinejaussoin/retro-board#112]
Forces you to use social media to login now. Internal server error when trying to auth via Github Screenshot attached. 
![image](https://user-images.githubusercontent.com/53021423/80387111-daaff980-886d-11ea-9f6c-a79f70728d5f.png)

**Comment by cindyccook** [comment]
![image](https://user-images.githubusercontent.com/53021423/80387001-b9e7a400-886d-11ea-83fa-460a18d3b4a0.png)

**Comment by antoinejaussoin** [comment]
Hi Cindy,

The app doesn't force you to login via social media at all, you can still login the "old" (and anonymous) way.

As for the error, I'll take a look but I had several users login in successfully over the weekend and today so might just be a glitch? Will investigate.

Thanks for reporting!

**Comment by cindyccook** [comment]
No, it's not really the old way. I can't see past sessions like I used to: This will create an anonymous account, but won't allow you to retrieve past sessions

**Comment by antoinejaussoin** [comment]
@cindyccook : you are half right: it's the same anonymous accounts as before, but because the mechanism to store past sessions has changed (it's now using the database and not your local storage), it cannot retrieve past sessions for anonymous accounts (as you would be able to see all the sessions by anyone who logged as "cindy" for instance).

I've got a plan to improve that though, so stay tuned.
