### ISSUE TITLE
Items blurred even if option is deactivated.

### ISSUE THREAD

**Issue by Xyaren** [antoinejaussoin/retro-board#148]
I just had a retro where some participants had blurred items, even if the option was deactivated.
Toggling the Option did not help.

For most participants it worked perfectly.

**Comment by antoinejaussoin** [comment]
Thanks for reporting this, I will wait and see if other people experience/report this, to make sure it's not just a glitch

**Comment by dallasgutauckis** [comment]
I'm on Firefox so I'm guessing maybe blur isn't the implementation, but I see "(hidden for now)" which is applied with a `::before` CSS selector. Is this the same issue?

**Comment by Xyaren** [comment]
Could be the same Issue. I did not have a chance to see the issue occurring myself.

**Comment by antoinejaussoin** [comment]
Thanks both for reporting this, I didn't realise before tonight how bad the bug was! Turns out it only happens on Firefox, but it made the whole product completely unusable on that browser.

I've just issued a fix, and will deploy it to retrospected.com in about 30 minutes.

Thanks again!

(@dallasgutauckis : It was indeed the problem: Firefox doesn't support blurring, so I had to make a "hack" that would only work on that browser, but I forgot to only apply that hack when the post is supposed to be blurred... instead it applied it all the time, hiding the content for all posts under Firefox.)
