### ISSUE TITLE
Thumbs icons don't appear in IE 11

### ISSUE THREAD

**Issue by dc99dc99** [antoinejaussoin/retro-board#20]
You see the numbers but not the thumbs which can be confusing for those who don't know what they mean

**Comment by dmorrisSL** [comment]
Here's how it looks in IE11:

![ie11_thumbs](https://cloud.githubusercontent.com/assets/20594993/19266687/9f4090b6-8fa2-11e6-8c5a-e5dc31046b33.GIF)

**Comment by antoinejaussoin** [comment]
Before I investigate any further, can you confirm you can see any of the other icons on IE11 within RBS?

I'm asking because RBS blocks these icons (it actually technically blocks web fonts, which these icons are made of). In most of the UI it's not obvious it does because the icons are not that important, so that's why it is possible you only noticed on these 2 buttons.

If it's the case, there's not much I can do, short of completely changing the icons but that would not be trivial for various reasons :)

<img width="1263" alt="retrospected_-_a_fun_way_to_retrospect" src="https://cloud.githubusercontent.com/assets/110254/19267808/b801fa1c-8fa8-11e6-9fe0-484e7dab9943.png">

**Comment by dmorrisSL** [comment]
Now you mention it, I can indeed see that _**none**_ of the icons are present.

As you say, the other icons aren't conspicuous by their absence because it's clear how the page works from its structure.

**Comment by antoinejaussoin** [comment]
It's a very annoying RBS-specific rule for IE. To mitigate, I would use Firefox, or the normal Chrome (not the RBS version of Chrome, as it's old and doesn't allow Javascript for external website).

**Comment by antoinejaussoin** [comment]
I'll close the issue, as it's unlikely to affect a huge number of people
