### ISSUE TITLE
Language is french on default

### ISSUE THREAD

**Issue by Xyaren** [antoinejaussoin/retro-board#313]
As the title says.
https://retrospected.com/ French is the default language for everyone, independent of the browser language.

**Comment by antoinejaussoin** [comment]
Thanks so much for the heads up, it was actually a misconfiguration on the server that redirected the naked domain (retrospected.com) to the beta website (beta.retrospected.com) instead of the regular one (www.)
This is now fixed, and I will add something later to make it more obvious when a user lands on the beta website...
