### ISSUE TITLE
Might be usefull to be able to cancel a session

### ISSUE THREAD

**Issue by Dewan2019** [antoinejaussoin/retro-board#72]
Hello,
So far i see no option for a contributor to delete a session, even if it is in the past.
The only otpion is to rename it in order to identify 
Would it be possible to include this option in a future release?
Have a good evening

**Comment by antoinejaussoin** [comment]
Hi,

Unfortunately this wouldn't really be feasible right now, because there's no such thing as a "real" account at the moment. Anyone can actually impersonate anyone else by taking the same name. So anyone could in theory delete any session.

That being said, I have on my roadmap a plan to add "real" sessions (with login/password or Github/Google/FB), and once that's done, I'll add the ability to delete a session.

Hope that makes sense!

**Comment by antoinejaussoin** [comment]
Will be done as part of #116
