### ISSUE TITLE
Customizing already created session

### ISSUE THREAD

**Issue by mschickensoup** [antoinejaussoin/retro-board#92]
At the moment, there is not option to customize the session one has already created. At the moment if you have created a session you **can't** do the following things:

- Change the text of your question
- Change number of columns
- Change an icon next to the textbox
- Change the number of likes / dislikes 

What do you think of it @antoinejaussoin ?

**Comment by antoinejaussoin** [comment]
These are actually pretty good ideas, with a few caveat: what if you reduce the number of columns and you already had posts there? Perhaps I could only allow increasing the number of columns, or reduce if the last column(s) are empty. Same for the number of likes/dislikes, otherwise you could end up with people who already voted too much (but I guess that's less of an issue).

Thanks for the suggestion though, I will probably integrate some of these on the v3 I'm working on at the moment (lots of change will be happening there!)

**Comment by mschickensoup** [comment]
Thanks for your thoughts @antoinejaussoin you are right that the described situation would be hard to overcome.

However, I was referring more to a situation where you create a new session as a creator/facilitator. In such case you are actually before sharing the link to the session with anyone (there are no cards in the columns yet) or before inviting people using their e-mail addresses. This might be the feature for a creator of a session and the creator can share rights of creator to the specific people. 

Does this make sense? 

Plus, I am super duper happy that you'd consider the suggestions on the v3 <3 Amazing!

**Comment by jghaanstra** [comment]
Looks like this didnt make the 3.1 release. Is this still something on the roadmap (and that is being actively developed) ?

**Comment by antoinejaussoin** [comment]
@jghaanstra , I'm just finishing implementing it, it will land in 3.2, watch this space :)
